### ISSUE TITLE
tenant is persisted in Sidekiq 4

### ISSUE THREAD

**Issue by twojustin** [ErwinM/acts_as_tenant#126] opened 2015-12-13 03:49 UTC
lets say i have,

```rb
class Company < ActiveRecord::Base
end

class SimpleWorker
  include Sidekiq::Worker

  def perform
    puts "start tenant = #{ActsAsTenant.current_tenant.try(:id)}"
    ActsAsTenant.current_tenant = Company.find(1)
    puts "end tenant = #{ActsAsTenant.current_tenant.try(:id)}"
  end
```

if i run the worker, `SimpleWorker.perform_async` repeatedly.  the output should be:
```
start tenant = 
end tenant = 1
start tenant = 
end tenant = 1
start tenant = 
end tenant = 1
...
```

after upgrading to sidekiq 4, the output i get is:
```
start tenant = 
end tenant = 1
start tenant = 1
end tenant = 1
start tenant = 1
end tenant = 1
...
```

it seems that each worker thread is holding onto the last tenant that it was set.  the middleware looks straight forward enough, and i've inspected the sidekiq queue job message.  the tenant is not be set in the message itself.  My best guess is that RequestStore is not been reset between each sidekiq worker run. or rather, each worker execution is not be defined as a "new request".

**Comment by ErwinM** [comment] 2016-03-19 07:50
I do not use sidekiq myself. Perhaps @davekaro could have a look?

**Comment by davekaro** [comment] 2016-03-19 12:29
I cannot reproduce this. I added a `SimpleWorker` just like yours above, opened up rails console and ran `SimpleWorker.perform_async` twice. Here is the output

```
2016-03-19T12:27:41.814Z 39504 TID-owt85p80o SimpleWorker JID-5f46df68f14fd2c5e399844f INFO: start
start tenant =
end tenant = 1
2016-03-19T12:27:41.868Z 39504 TID-owt85p80o SimpleWorker JID-5f46df68f14fd2c5e399844f INFO: done: 0.054 sec
2016-03-19T12:27:46.666Z 39504 TID-owt85p78w SimpleWorker JID-a3fed97b7ff7af44e2d578a2 INFO: start
start tenant =
end tenant = 1
2016-03-19T12:27:46.668Z 39504 TID-owt85p78w SimpleWorker JID-a3fed97b7ff7af44e2d578a2 INFO: done: 0.002 sec
```

**Comment by davekaro** [comment] 2016-03-19 12:31
Ahh. I was on Sidekiq 4.0.1, after upgrading to 4.1.1 the problem exists. Will dig a little deeper.

**Comment by davekaro** [comment] 2016-03-19 12:38
Never mind, sorry. It is happening in other versions of 4.0.x and 4.1.x as well. But only intermittently.

**Comment by davekaro** [comment] 2016-03-21 16:29
On second thought, @twojustin I don't think you should use the `current_tenant=` setter in the worker. Instead, either set the `current_tenant` before scheduling your job (in which case, the middleware will properly set the correct tenant in the job), or if you want to change the tenant or manually set it in the worker, then use `ActsAsTenant.with_tenant` and pass a block (https://github.com/ErwinM/acts_as_tenant#setting-the-current-tenant-for-a-block). That will ensure the worker thread resets the `current_tenant` back to `nil` after it executes.

My guess is sidekiq is reusing the same thread to execute 2 separate jobs. If you modify the `current_tenant` in that thread, it will persist to the next job.

@ErwinM I believe you can close this.

**Comment by ErwinM** [comment] 2016-03-27 08:37
@davekaro thx for your help

**Closed by ErwinM** 2016-03-27 08:37 UTC
Labels: Investigating

**Comment by twojustin** [comment] 2016-06-16 23:56
@davekaro thank you for looking into this. 
@ErwinM please consider #141, which will fix this issue.
